// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package [module].actions;

import org.json.JSONObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Create a JSON object and return it as a string.
 *
 * Example:
 * {
 *     "parent": {
 *         "propOne": "Hello World",
 *         "propTwo": "012345"
 *     }
 * }
 *
 * @uses https://mvnrepository.com/artifact/org.json/json (JSON in Java package)
 *
 * @return JSON string
 */
public class Create_JSON extends CustomJavaAction<java.lang.String>
{
	private java.lang.String PropOne;
	private java.math.BigDecimal PropTwo;

	public Create_JSON(IContext context, java.lang.String PropOne, java.math.BigDecimal PropTwo)
	{
		super(context);
		this.PropOne = PropOne;
		this.PropTwo = PropTwo;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String jsonstring = "";

		// Define parent object
		JSONObject parent = new JSONObject();

		// Add properties
		parent.put("propOne", this.PropOne);
		parent.put("propTwo", this.PropTwo);

		// Define root object
		JSONObject root = new JSONObject();

		// Add parent to root
		root.put("parent", parent);

		// Convert JSON to string
		jsonstring = root.toString();

		return jsonstring;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Create_JSON";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
