// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package [module].actions;

import org.json.JSONObject;
import org.json.JSONPointer;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Create a JSON object and return it as a string.
 *
 * Example:
 * {
 *     "parent": {
 *         "propOne": "Hello World",
 *         "propTwo": [ "012345", "123456" ]
 *     }
 * }
 *
 * With path "/parent/propTwo/1" --> "123456"
 *
 * @uses https://mvnrepository.com/artifact/org.json/json (JSON in Java package)
 *
 * @return Property string
 */
public class Read_JSON extends CustomJavaAction<java.lang.String>
{
	private java.lang.String JSONString;
	private java.lang.String Path;

	public Read_JSON(IContext context, java.lang.String JSONString, java.lang.String Path)
	{
		super(context);
		this.JSONString = JSONString;
		this.Path = Path;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String jsonstring = "";
		String root = this.JSONString;
		String path = this.Path;

		// Wrap JSON array to ensure a single JSON object
		if (root.trim().startsWith("[")) {
			root = "{list:" + root + "}";
			path = "/list" + path.trim();
		}

		// Create JSON object
		JSONObject json = new JSONObject(root);

		// Use path to point to the property
		JSONPointer pointer = new JSONPointer(path);

		// Parse object and always return a string
		jsonstring = json.optQuery(pointer).toString();

		return jsonstring;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Read_JSON";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
